### ISSUE TITLE
Link de referência para ARIA11 desatualizado

### ISSUE THREAD

**Issue by livingatrip** [amagovpt/access-monitor-plus#24]
Olá!

Primeiramente, parabéns pelo projeto! Gostei muito e estou utilizando para análise do site da empresa em que trabalho e para outros projetos pessoais também. 

Recentemente notei um link desatualizado para o item ARIA11. O link aponta para https://www.w3.org/WAI/standards-guidelines/act/rules/ARIA11/, que no momento está retornando o erro 404. Pelo que pude notar, o conteúdo deste item agora está localizado em: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA11. Clonei o projeto e fiz uma análise superficial para identificar se seria uma atualização simples, mas percebi que o retorno desse link é de forma genérica e concatena na função refWebsiteACT, então optei por abrir este issue para discutirmos uma solução ou apenas deixar listado esse problema para futuras atualizações.

![image](https://github.com/amagovpt/access-monitor-plus/assets/45071084/6dce27a5-4450-443c-9aa6-78b49dbd7e36)

Qualquer dúvida estou à disposição!

Atenciosamente,

PH.

**Comment by carlosapaduarte** [comment]
Obrigado pelo aviso. Será corrigido quando disponibilizarmos a próxima versão.

**Comment by carlosapaduarte** [comment]
Corrigido em https://github.com/amagovpt/access-monitor-plus/commit/8953158d96d4dbc6f70b5ca7359c7412aeb79922
