### ISSUE TITLE
Url deixou de dar

### ISSUE THREAD

**Issue by ivoprotasioAltyra** [amagovpt/access-monitor-plus#34]
Boa tarde,

Desculpem incomodar, queria informar e pedir ajuda acerca da seguinte situação:

O url a seguir anteriormente (há uns dias) funcionava mas agora dá o erro abaixo:
- https://pan.espap.gov.pt/

![image](https://github.com/user-attachments/assets/b559ead1-94b5-4e97-a567-859c0d395c39)

Este url, por exemplo, funciona:
- https://cncp.espap.gov.pt/

Poderá ter algo a ver com os caracteres especiais no título, no url, na página em si?

Obrigado e cumprimentos,
Ivo Protásio

**Comment by joanacarvalho50** [comment]
Bom dia. Aqui estava à funcionar até semana passada, urls simples funcionam, por exemplo, https://www.publico.pt/, mas as urls secundárias,como a https://www.publico.pt/mundo , apresentam o erro 404.

**Comment by carlosapaduarte** [comment]
@ivoprotasioAltyra, obrigado pelo aviso. Depois da última atualização, já se consegue fazer aa avaliação.

**Comment by ivoprotasioAltyra** [comment]
Eu é que agradeço pelas respostas e pela resolução! Confimo que funciona :)
